version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-recipes
    restart: always
    environment:
      POSTGRES_DB: recipes
      POSTGRES_USER: recipes_user
      POSTGRES_PASSWORD: recipes_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  play-app:
    build: .
    container_name: play-app
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/recipes
      DB_USER: recipes_user
      DB_PASSWORD: recipes_password
    ports:
      - "9000:9000"
    command: sbt run

volumes:
  postgres-data: