version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-recipes
    restart: always
    environment:
      POSTGRES_DB: recipes
      POSTGRES_USER: recipes_user
      POSTGRES_PASSWORD: recipes_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: